channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=23.0.1
- pip:
  - mlflow==2.16.2
  - catboost==1.2.7
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
